### ISSUE TITLE
It´s not working with symfony 3.*

### ISSUE THREAD

**Issue by ikerib** [mablae/DatetimepickerBundle#1]

**Comment by mablae** [comment]
Hey @ikerib 

Thanks for the feedback. Can you provide any details? I am still using v2.8

Also there are some other issues I am aware of like not matching Month names with french Version of moment.js.

**Comment by ikerib** [comment]
it says it´s requieres symfony 2.9.\* or something like that (I´m not in my computer right now...)

**Comment by mablae** [comment]
Yeah the installation is not working, which is correct, since I didn't test the bundle with Symfony3 yet.

It needs a slight change in the composer.json to allow both Symfony2 versions.

**Comment by mablae** [comment]
Solved by merging #2
